services:
  backend:
    depends_on:
      - db
    build: 
      context: .
    container_name: flask
    ports:
      - 8080:8080
    
    volumes:
      - ./:/opt/app:rw
  
  db:
    image: mysql
    container_name: mysql
    ports:
      - 36000:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql